ALTER TABLE users
    ADD COLUMN password VARCHAR NOT NULL;
ALTER TABLE users
    ADD COLUMN first_name VARCHAR(64) NOT NULL;
ALTER TABLE users
    ADD COLUMN last_name VARCHAR(128) NOT NULL;
ALTER TABLE users
    ADD COLUMN birthdate DATE NOT NULL;
ALTER TABLE users
    ADD COLUMN email VARCHAR(128) NOT NULL;
